Repository Interencheres/cpm-logger, pull requests merged in 2018-12, with the labels that each got.

#16 fix(cpmHeaders): Disable debug message on status page
  logger.js
Labels: status:review-ok

#18 Feat/disable log on status route
  logger.js
Labels: status:second-validation, type:feature

#15 fix(dependencies): upgrade morgan version
  package.json
Labels: status:second-validation, type:fix
